# Generated by Django 5.0 on 2025-04-20 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_alter_product_tool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tool',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='tools.tool'),
        ),
    ]
